// Built-in training templates a user can start from instead of building a
// training from scratch (see AddCategoryModal). Each template's fields()/
// steps() return freshly-id'd objects on every call, so using the same
// template for multiple dogs (or re-adding one that was deleted) never
// produces id collisions.

function templateField(label, type, unit) {
  return { id: uid(), label, type, unit: unit || "" };
}

function templateStep(label, taskLabels) {
  return { id: uid(), label, tasks: taskLabels.map((t) => ({ id: uid(), label: t })) };
}

const TRAINING_TEMPLATES = [
  {
    id: "relaxation-protocol",
    icon: "🧘",
    name: "Relaxation Protocol",
    source: "Karen Overall's Protocol for Relaxation (Manual of Clinical Behavioral Medicine for Dogs and Cats)",
    description:
      "The real 15-day sit-and-settle protocol, task for task: small steps and sounds building up to doors, absences, the doorbell, and pretend visitors. Your dog should already hold a calm sit-stay for 15 seconds before starting. Pick your day and check off each task as you go.",
    fields: () => [templateField("Session length", "number", "min"), templateField("How relaxed?", "scale")],
    steps: () => [
      templateStep("Day 1 — Sit-stays with small steps and sounds", ["Sit for 2 seconds", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you take 1 step back and then return", "Sit while you take 2 steps back and then return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you take 1 step to the right and then return", "Sit while you take 1 step to the left and then return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you take 2 steps back and return", "Sit while you take 2 steps to the right and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you take 2 steps to the left and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you clap your hands softly once", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you take 3 steps back and return", "Sit while you count out loud to 3", "Sit while you count out loud to 5", "Sit while you count out loud to 10", "Sit while you clap your hands softly once", "Sit while you count out loud to 5", "Sit while you count out loud to 10", "Sit while you count out loud to 5", "Sit while you count out loud to 10", "Sit while you count out loud to 20", "Sit while you take 3 steps to the right and return", "Sit while you clap your hands softly twice", "Sit for 3 seconds", "Sit for 5 seconds", "Sit while you take 1 step back and return", "Sit for 3 seconds", "Sit for 10 seconds", "Sit for 5 seconds", "Sit for 3 seconds"]),
      templateStep("Day 2 — More distance and movement", ["Sit for 5 seconds", "Sit for 10 seconds", "Sit while you take 1 step back and return", "Sit while you take 3 steps back and return", "Sit for 10 seconds", "Sit while you take 3 steps to the right and return", "Sit while you take 3 steps to the left and return", "Sit for 10 seconds", "Sit while you take 3 steps to the right and clap your hands", "Sit while you take 3 steps to the left and clap your hands", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you walk one-quarter of the way around the dog to the right", "Sit while you take 4 steps back", "Sit while you walk one-quarter of the way around the dog to the left", "Sit for 10 seconds", "Sit while you take 5 steps back from the dog, clapping your hands, and return", "Sit while you walk halfway around the dog to the right and return", "Sit while you walk halfway around the dog to the left and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you jog quietly in place for 3 seconds", "Sit while you jog quietly in place for 5 seconds", "Sit while you jog quietly in place for 10 seconds", "Sit for 10 seconds", "Sit while you jog one-quarter of the way around the dog to the right and return", "Sit while you jog one-quarter of the way around the dog to the left and return", "Sit for 5 seconds", "Sit for 10 seconds"]),
      templateStep("Day 3 — Bigger distances and jogging", ["Sit for 10 seconds", "Sit for 15 seconds", "Sit while you take 2 steps backwards and return", "Sit while you jog 5 steps backwards from the dog and return", "Sit while you walk halfway around the dog to the right and return", "Sit while you walk halfway around the dog to the left and return", "Sit while you take 10 steps backwards and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you take 10 steps to the left and return", "Sit while you take 10 steps to the right and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit for 20 seconds", "Sit while you walk halfway around the dog to the right, clap your hands, and return", "Sit for 20 seconds", "Sit while you walk halfway around the dog to the left, clap your hands, and return", "Sit for 10 seconds", "Sit while you jog 10 steps to the right and return", "Sit while you jog 10 steps to the left and return", "Sit while you jog in place for 10 seconds", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you jog in place for 20 seconds", "Sit for 10 seconds", "Sit while you jog backwards 5 steps and return", "Sit while you jog to the right 5 steps and return", "Sit while you jog to the left 5 steps and return", "Sit for 5 seconds while you clap your hands", "Sit for 10 seconds while you clap your hands", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 4 — Longer holds and full circles", ["Sit for 5 seconds", "Sit for 10 seconds", "Sit while you jog backwards 5 steps and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 20 seconds", "Sit while you jog halfway around the dog to the right and return", "Sit while you jog halfway around the dog to the left and return", "Sit while you move three-quarters of the way around the dog to the right and return", "Sit while you move three-quarters of the way around the dog to the left and return", "Sit while you jog backwards 5 steps, clapping your hands, and return", "Sit for 10 seconds", "Sit for 15 seconds", "Sit while you clap your hands for 20 seconds", "Sit while you quickly move backwards 10 steps and return", "Sit while you quickly move backwards 15 steps and return", "Sit for 20 seconds", "Sit while you jog halfway around the dog to the right and return", "Sit while you jog halfway around the dog to the left and return", "Sit while you quickly walk 15 steps to the left and return", "Sit while you quickly walk 15 steps to the right and return", "Sit for 20 seconds", "Sit while you move three-quarters of the way around the dog to the right and return", "Sit while you move three-quarters of the way around the dog to the left and return", "Sit while you walk all the way around the dog", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you walk approximately 20 steps to an entrance, clapping your hands, and return", "Sit while you walk around the dog, quietly clapping your hands, and then return", "Sit for 20 seconds", "Sit while you quickly jog around the dog", "Sit for 20 seconds", "Sit for 10 seconds while you clap your hands"]),
      templateStep("Day 5 — Entrances and doorways", ["Sit for 5 seconds", "Sit for 15 seconds", "Sit while you walk quickly 15 steps to the right and return", "Sit while you walk quickly 15 steps to the left and return", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you walk approximately 20 steps to an entrance, clapping your hands, and return", "Sit for 20 seconds", "Sit while you walk around the dog, clapping your hands", "Sit for 20 seconds", "Sit for 10 seconds", "Sit while you walk quickly backwards, clapping your hands, and return", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you walk approximately 20 steps to an entrance, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit for 10 seconds", "Sit while you walk quickly backwards, clapping your hands, and return", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you walk approximately 20 steps to an entrance, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit for 20 seconds", "Sit while you walk approximately 20 steps to an entrance, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit for 10 seconds", "Sit while the doorknob is touched, or you move into the entryway, and return", "Sit for 10 seconds", "Sit for 15 seconds while you clap your hands", "Sit for 10 seconds while you jog in place", "Sit for 5 seconds"]),
      templateStep("Day 6 — Going through the door", ["Sit for 10 seconds", "Sit for 20 seconds while you jog back and forth in front of the dog", "Sit for 15 seconds", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you walk quickly backwards, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit for 20 seconds while jogging", "Sit while you walk around the dog", "Sit while you walk around the dog clapping your hands", "Sit for 15 seconds", "Sit for 20 seconds", "Sit for 30 seconds", "Sit while you walk quickly backwards, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit while you open the door or go into the entrance for 5 seconds and then return", "Sit while you open the door or go into the entrance for 10 seconds and then return", "Sit for 30 seconds", "Sit while you walk quickly backwards, clapping your hands, and return", "Sit while you go to an entrance and just touch the doorknob or wall, and return", "Sit for 10 seconds", "Sit while you go through the door or the entranceway and then return", "Sit while you go through the door or the entranceway, clapping your hands, and then return", "Sit while you open the door or go into the entrance for 10 seconds and then return", "Sit for 30 seconds", "Sit while you disappear from view for 5 seconds and then return", "Sit for 20 seconds", "Sit for 10 seconds while you clap your hands", "Sit for 5 seconds"]),
      templateStep("Day 7 — Longer absences", ["Sit for 10 seconds", "Sit for 20 seconds while you clap your hands", "Sit while you take 10 steps backwards and return", "Sit while you walk around the dog", "Sit while you go through the door or the entranceway and then return", "Sit while you go through the door or the entranceway, clapping your hands, and then return", "Sit while you open the door or go into the entrance for 10 seconds and then return", "Sit for 30 seconds", "Sit while you disappear from view for 5 seconds and then return", "Sit while you go through the door or the entranceway and then return", "Sit while you go through the door or the entranceway, clapping your hands, and then return", "Sit while you open the door or go into the entrance for 10 seconds and then return", "Sit for 10 seconds", "Sit for 20 seconds", "Sit for 30 seconds", "Sit while you disappear from view for 10 seconds and then return", "Sit while you disappear from view for 15 seconds and then return", "Sit for 10 seconds", "Sit for 15 seconds", "Sit for 5 seconds while you clap your hands", "Sit while you jog in place for 10 seconds", "Sit while you jog three-quarters of the way around to the right and return", "Sit while you jog three-quarters of the way around to the left and return", "Sit while you go through the door or the entranceway, clapping your hands, and then return", "Sit while you open the door or go into the entrance for 10 seconds and then return", "Sit for 30 seconds", "Sit while you disappear from view for 15 seconds and then return", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 8 — Sitting in a chair nearby", ["Sit for 10 seconds", "Sit for 15 seconds while you jog and clap your hands", "Sit while you back up 15 steps and return", "Sit while you circle the dog and return", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit for 5 seconds", "Sit for 5 seconds while you sit in a chair placed 5 feet from the dog", "Sit for 5 seconds", "Sit for 15 seconds while you jog and clap your hands", "Sit while you back up 15 steps and return", "Sit while you circle the dog and return", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 30 seconds and return", "Sit for 5 seconds", "Sit while you circle the dog and return", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit for 5 seconds while you sit in a chair near the dog", "Sit while you disappear from view for 10 seconds, sit in the chair for 5 seconds, and return", "Sit for 10 seconds", "Sit for 20 seconds while you jog and clap", "Sit for 15 seconds while you run around", "Sit for 10 seconds", "Sit for 5 seconds while you turn around", "Sit for 5 seconds while you sit in a chair near the dog", "Sit while you disappear from view for 10 seconds, sit in the chair for 5 seconds, and return", "Sit for 10 seconds"]),
      templateStep("Day 9 — Circling, jogging, stretching", ["Sit for 5 seconds", "Sit for 10 seconds while you turn around", "Sit for 5 seconds while you jog", "Sit while you walk around the dog", "Sit while you jog around the dog", "Sit while you jog around the dog, clapping your hands", "Sit while you jog twice around the dog", "Sit for 10 seconds", "Sit for 15 seconds while you clap your hands", "Sit for 20 seconds", "Sit while you move three-quarters of the way around the dog to the right and return", "Sit while you move three-quarters of the way around the dog to the left and return", "Sit while you disappear from view for 10 seconds and then return", "Sit while you circle the dog and return", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit for 5 seconds while you sit in a chair near the dog", "Sit while you disappear from view for 10 seconds, sit in the chair for 5 seconds, and return", "Sit for 10 seconds", "Sit while you bend down and touch your toes", "Sit while you stretch your arms", "Sit while you stretch your arms and jump once", "Sit while you touch your toes 5 times", "Sit while you stretch your arms and jump 3 times", "Sit for 15 seconds", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 10 — Leaving the dog's view", ["Sit for 5 seconds and clap", "Sit for 10 seconds while you touch your toes", "Sit for 15 seconds while you sit in a chair", "Sit while you walk quickly 15 steps to the right and return", "Sit while you walk quickly 15 steps to the left and return", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you leave the dog's view for 5 seconds and return", "Sit while you leave the dog's view for 10 seconds and return", "Sit while you leave the dog's view for 15 seconds and return", "Sit for 10 seconds", "Sit for 5 seconds", "Sit while you walk quickly 15 steps to the right and return", "Sit while you walk quickly 15 steps to the left and return", "Sit while you walk approximately 20 steps to an entrance and return", "Sit while you leave the dog's view for 5 seconds and return", "Sit while you leave the dog's view for 10 seconds and return", "Sit while you leave the dog's view for 15 seconds and return", "Sit while you leave the dog's view for 5 seconds, knock softly on the wall, and return", "Sit for 5 seconds", "Sit while you leave the dog's view for 5 seconds and return", "Sit while you leave the dog's view for 10 seconds and return", "Sit while you leave the dog's view for 15 seconds and return", "Sit while you leave the dog's view for 5 seconds, knock softly on the wall, and return", "Sit while you leave the dog's view, quickly knock softly on the wall, and return", "Sit for 5 seconds", "Sit while you leave the dog's view for 10 seconds, knock softly on the wall, and return", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 11 — Knocking and the doorbell", ["Sit for 5 seconds", "Sit for 10 seconds", "Sit while you leave the dog's view, quickly knock softly on the wall, and return", "Sit for 5 seconds", "Sit while you leave the dog's view for 10 seconds, knock softly on the wall, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 2 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 5 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 10 seconds, and return", "Sit for 5 seconds while you jog", "Sit while you walk around the dog", "Sit while you jog around the dog", "Sit while you jog around the dog, clapping your hands", "Sit while you jog twice around the dog", "Sit for 10 seconds", "Sit for 15 seconds while you clap your hands", "Sit for 20 seconds", "Sit while you move three-quarters of the way around the dog to the right and return", "Sit while you move three-quarters of the way around the dog to the left and return", "Sit while you disappear from view for 10 seconds and then return", "Sit while you circle the dog and return", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 12 — Humming and longer absences", ["Sit for 10 seconds", "Sit for 5 seconds while you clap your hands", "Sit for 15 seconds", "Sit for 20 seconds while you hum", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit for 5 seconds while you sit in a chair near the dog", "Sit while you disappear from view for 10 seconds, sit in the chair for 5 seconds, and return", "Sit for 15 seconds", "Sit for 20 seconds while you hum", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit while you move three-quarters of the way around the dog to the right and return", "Sit while you move three-quarters of the way around the dog to the left and return", "Sit while you disappear from view for 10 seconds and then return", "Sit while you circle the dog and return", "Sit for 10 seconds", "Sit while you leave the dog's view, quickly knock softly on the wall, and return", "Sit for 5 seconds", "Sit while you leave the dog's view for 10 seconds, knock softly on the wall, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 2 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, say \"hello,\" and return", "Sit while you leave the dog's view, say \"hello,\" wait 3 seconds, and return", "Sit for 10 seconds", "Sit for 5 seconds"]),
      templateStep("Day 13 — Doorbell and \"hello\"", ["Sit for 5 seconds", "Sit for 15 seconds while you hum", "Sit for 15 seconds while you hum and clap", "Sit while you disappear from view for 20 seconds and return", "Sit while you disappear from view for 25 seconds and return", "Sit for 5 seconds while you sit in a chair near the dog", "Sit while you disappear from view for 10 seconds, sit in the chair for 5 seconds, and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you leave the dog's view, quickly knock softly on the wall, and return", "Sit for 5 seconds", "Sit while you leave the dog's view for 10 seconds, knock softly on the wall, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 2 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, say \"hello,\" wait 5 seconds, and return", "Sit while you leave the dog's view, knock or ring the bell, say \"hello,\" wait 5 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, say \"hello,\" wait 5 seconds, and return", "Sit while you leave the dog's view, knock or ring the bell, say \"hello,\" wait 5 seconds, and return", "Sit for 20 seconds while you hum", "Sit for 15 seconds while you clap", "Sit for 5 seconds", "Sit while you jog around the dog", "Sit for 10 seconds while you clap and hum", "Sit for 5 seconds while you jog in place", "Sit while you jog around the dog, humming"]),
      templateStep("Day 14 — Knocking, bell, and talking", ["Sit for 10 seconds", "Sit for 10 seconds", "Sit for 5 seconds while you hum and clap", "Sit while you run around the dog", "Sit while you walk back and forth to the door", "Sit while you leave the room and quickly knock or ring the bell, and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit for 10 seconds", "Sit for 5 seconds while you hum and clap", "Sit while you run around the dog", "Sit while you walk back and forth to the door", "Sit while you leave the room and quickly knock or ring the bell, and return", "Sit for 5 seconds", "Sit for 10 seconds", "Sit while you leave the dog's view for 10 seconds, knock softly on the wall, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, ring the doorbell, and immediately return", "Sit while you leave the dog's view, ring the doorbell, wait 2 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, say \"hello,\" wait 5 seconds, and return", "Sit while you leave the dog's view, knock or ring the bell, say \"hello,\" wait 10 seconds, and return", "Sit for 30 seconds", "Sit while you leave the dog's view, say \"hello,\" wait 10 seconds, and return", "Sit while you leave the dog's view, knock or ring the bell, say \"hello,\" wait 10 seconds, and return", "Sit for 20 seconds while you hum", "Sit for 20 seconds", "Sit for 5 seconds"]),
      templateStep("Day 15 — Visitors and goodbyes", ["Sit for 10 seconds", "Sit for 5 seconds", "Sit for 15 seconds while you clap and hum", "Sit while you leave the dog's view, knock or ring the bell, say \"hello,\" talk for 10 seconds, and return", "Sit for 20 seconds while you hum", "Sit while you leave the dog's view, say \"hello,\" invite the invisible person in, wait 5 seconds, and return", "Sit for 10 seconds", "Sit for 5 seconds", "Sit while you leave the dog's view, say \"hello,\" invite the invisible person in, wait 10 seconds, and return", "Sit while you leave the dog's view, say \"hello,\" talk as if to someone for 5 seconds, and return", "Sit for 5 seconds while you hum and clap", "Sit while you run around the dog", "Sit while you walk back and forth to the door", "Sit while you leave the room and quickly knock or ring the bell, and return", "Sit for 5 seconds", "Sit while you leave the room and knock or ring the bell for 3 seconds, and return", "Sit while you leave the room and knock or ring the bell for 5 seconds", "Sit while you leave the room and talk to people who aren't there for 3 seconds", "Sit while you leave the room and talk to people who aren't there for 5 seconds", "Sit while you leave the room and talk to people who aren't there for 10 seconds", "Sit while you run around the dog", "Sit for 10 seconds while you sit in a chair", "Sit for 30 seconds while you sit in a chair", "Sit for 15 seconds while you jog and clap", "Sit for 5 seconds"]),
    ],
  },
  {
    id: "settle-on-a-mat",
    icon: "🟫",
    name: "Settle on a mat",
    source: null,
    description:
      "Teach the dog that a mat or bed is a cue to lie down and relax — useful for mealtimes, visitors, or out in public.",
    fields: () => [templateField("Duration", "number", "min"), templateField("Distractions handled", "scale")],
    steps: () => [
      templateStep("Step 1 — Notice the mat", ["Look at, sniff, or step toward the mat"]),
      templateStep("Step 2 — Get on the mat", ["All four feet on the mat"]),
      templateStep("Step 3 — Sit or down on the mat", ["Sit or down on the mat"]),
      templateStep("Step 4 — Add duration", ["Stay on the mat a few seconds", "Stay on the mat longer"]),
      templateStep("Step 5 — Add distance", ["Step away, then return", "Step further away, then return"]),
      templateStep("Step 6 — Add distractions", ["A toy or object moves nearby", "Another person walks around"]),
      templateStep("Step 7 — Take it on the road", [
        "Practice in a new room",
        "Practice somewhere out of the house (café, park bench, vet waiting room)",
      ]),
    ],
  },
];
